### PR TITLE
Add sensible-defaults gitignore file.

### PR DESCRIPTION
**Pull request by bserem**
I believe it would be nice to have a default .gitignore file in this project. This PR solves exactly that, based on the drupal composer project.

The example.gitignore file that exists in Drupal core is not "ready to use" as it is not compatible with a relocated document root.

### CODE REVIEW

**Comment by frob** [comment]
This does more than add a .gitignore it also adds to the composer.json

**Comment by bserem** [comment]
@frob  this is actually not my doing.
My commit is this: https://github.com/drupal/recommended-project/pull/2/commits/e6903043a8e756e4f77912629999de0b1b2c0c89

Then somehow this happened:
image
which somehow predates my PR by 2 months but was not there on the time the PR was made.

In any case, I am more than happy to re-do the PR but I do not think anybody is monitoring this.

**Comment by frob** [comment]
I see, I think the issues are being tracked on d.o and github now has the ability for project maintainers to commit to PR branches. I tried to open an issue but I couldn't find the right component from the drupal core issue component drop down of doom.

You're probably right.

**Comment by drumm** [comment]
Issues are indeed only tracked only on Drupal.org. This repository is auto-generated based on https://git.drupalcode.org/project/drupal/-/tree/8.8.x/composer%2FTemplate%2FRecommendedProject, so I think that would be the place to add this. https://www.drupal.org/project/drupal/issues/3082958 looks like an existing issue for this.

**Pull request closed without merging**
